env:
  browser: true
  es2021: true
extends:
  - prettier
  - standard
  - eslint:recommended
  - plugin:jest/recommended
plugins:
  - 'prettier'
parserOptions:
  ecmaVersion: 12
  sourceType: module
  parser: 'babel-eslint'
  allowImportExportEverywhere: true
rules:
  {
    prettier/prettier: 2,
    no-console: 1,
    eqeqeq: 2,
    no-eq-null: 1,
    no-multi-spaces: 1,
    camelcase: 1,
    semi: 0,
    comma-dangle: 0,
    space-before-function-paren: 0,
    max-len: ['error', { code: 135, ignoreComments: true, ignoreUrls: true }],
    indent: 0,
    curly: [0, 'multi'],
  }
